packages:
  - 'packages/*'
  - 'plugins/from/*'
  - 'plugins/transform/*'
  - 'plugins/to/*'
  - 'tests/*'
allowBuilds:
  esbuild: true
  nx: true
minimumReleaseAgeExclude:
  - '@feishux/api@0.4.0'
  - '@feishux/doc-to-md@0.4.0'
  - '@feishux/shared@0.4.0'
