name: CI
on:
  push:
    branches: ['v1']
  pull_request:
    branches: ['v1']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
        with:
          version: 11
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Verify Change Logs
        run: npx changeset status --since=origin/v1
      - name: Build
        run: pnpm turbo build --force
